---
- name: Setup Portainer Controller on Proxmox VM
  hosts: localhost
  become: yes
  tasks:

    - name: Install required dependencies
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - python3-pip  # Ensure pip is installed
        state: present
        update_cache: yes

    - name: Add Docker GPG Key
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null
        chmod a+r /etc/apt/keyrings/docker.asc
      args:
        executable: /bin/bash

    - name: Add Docker repository
      shell: |
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_lsb.codename }} stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Install Docker and dependencies
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Ensure Python Docker SDK is installed
      pip:
        name: docker
        state: present

    - name: Create Portainer data directory
      file:
        path: /opt/portainer/data
        state: directory
        mode: '0755'

    - name: Deploy Portainer container
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        state: started
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9443:9443"
          - "9000:9000"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
          - "/opt/portainer/data:/data"

    - name: Verify Portainer is running
      shell: "docker ps | grep portainer"
      register: portainer_status
      changed_when: false

    - name: Display Portainer status
      debug:
        msg: "Portainer is running! Access it at https://{{ ansible_default_ipv4.address }}:9443"
